version: '3.4'

services:
  pgadmin:
    image: dpage/pgadmin4
  portainer:
    image: portainer/portainer-ce
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres
  discountapi:
    image: discountapi
    build:
      context: .
      dockerfile: src/Services/Discount/DiscountAPI/Dockerfile
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/CatalogAPI/Dockerfile
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/BasketAPI/Dockerfile
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: