version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/CatalogAPI/Dockerfile
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/BasketAPI/Dockerfile
volumes:
  mongo_data:
