# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  discountapi:
    container_name: discountapi
    image: discountapi
    build: 
      context: .
      dockerfile: src/Services/Discount/DiscountAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSetting:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;Password=admin1234;User Id=admin
    depends_on:
      - discountdb
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  basketapi:
    container_name: basketapi
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/BasketAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionString=basketdb:6379
      - GrpcSettings:DiscountUrl=http://discountgrpc:8003
      - RabbitMq__Host=rabbitmq
    depends_on:
      - basketdb
      - rabbitmq
  discountgrpc:
    container_name: discountgrpc
    image: discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/DiscountGrpc/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8003:80
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - port=8003
      - DatabaseSetting:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;Password=admin1234;User Id=admin
  orderapi:
    container_name: orderapi
    image: orderapi
    build: 
      context: .
      dockerfile: src/Services/Ordering/OrderingAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8004:80
    depends_on:
      - orderdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings:SqlServer=TrustServerCertificate=True;Server=orderdb;Database=OrderDb;User Id = sa;Password=ChloeWithout3
  catalogapi:
    container_name: catalogapi
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/CatalogAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:80
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  orderdb:
    container_name: orderdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ChloeWithout3
    ports:
      - 1433:1433
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin