# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  catalogapi:
    container_name: catalogapi
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/CatalogAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:80
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
