version: '3.4'

services:
  pgadmin:
    image: dpage/pgadmin4
  portainer:
    image: portainer/portainer-ce
  catalogdb:
    image: mongo
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres
  discountapi:
    image: discountapi
    build:
      context: .
      dockerfile: src/Services/Discount/DiscountAPI/Dockerfile
  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: src/Services/Ordering/OrderingAPI/Dockerfile
  discountgrpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/DiscountGrpc/Dockerfile
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/CatalogAPI/Dockerfile
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/BasketAPI/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management-alpine
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: